

const searchList = 
[ 
     {"ticker": "A", "name": "Agilent"},
     {"ticker": "AAL", "name": "American Airlines"},
     {"ticker": "AAPL", "name": "Apple"},
     {"ticker": "ABB", "name": "Abb Ltd"},
     {"ticker": "ABC", "name": "AmerisourceBergn"},
     {"ticker": "ABEV", "name": "Ambev"},
     {"ticker": "ABNB", "name": "Airbnb"},
     {"ticker": "ABT", "name": "Abbot Laboratories"},
     {"ticker": "ABV", "name": "AbbVie"},
     {"ticker": "ACB", "name": "Aurora Cannabis"},
     {"ticker": "ACGL", "name": "Arch Capital Group"},
     {"ticker": "ACN", "name": "Accenture plc Class A"},
     {"ticker": "ACST", "name": "Acasti Pharma"},
     {"ticker": "ADBE", "name": "Adobe"},
     {"ticker": "ADI", "name": "Analog Devices"},
     {"ticker": "ADM", "name": "Archer-Daniels-Midland"},
     {"ticker": "ADP", "name": "Automatic Data Processing"},
     {"ticker": "ADSK", "name": "Autodesk"},
     {"ticker": "AEE", "name": "Ameren"},
     {"ticker": "AEM", "name": "Agnico Eagle Mines"},
     {"ticker": "AEP", "name": "American Electric Power"},
     {"ticker": "AES", "name": "AES"},
     {"ticker": "AFRM", "name": "Affirm Holdings"},
     {"ticker": "AGR", "name": "Avangrid"},
     {"ticker": "AIG", "name": "American International Group"},
     {"ticker": "AJG", "name": "Arthur J Gallagher"},
     {"ticker": "AKAM", "name": "Akamai Technologies"},
     {"ticker": "ALB", "name": "Albemarle"},
     {"ticker": "ALC", "name": "Alcon"},
     {"ticker": "ALGN", "name": "Align"},
     {"ticker": "ALL", "name": "Allstate"},
     {"ticker": "ALLY", "name": "Ally Financial"},
     {"ticker": "ALNY", "name": "Alnylam Pharmaceuticals"},
     {"ticker": "ALXN", "name": "Alexion"},
     {"ticker": "AMAT", "name": "Applied Materials"},
     {"ticker": "AMC", "name": "AMC Entertainment"},
     {"ticker": "AMCR", "name": "Amcor"},
     {"ticker": "AMCX", "name": "AMC Networks"},
     {"ticker": "AMD", "name": "Advanced Micro Devices"},
     {"ticker": "AME", "name": "AMTEK"},
     {"ticker": "AMGN", "name": "Amgen"},
     {"ticker": "AMJ", "name": "JPMorgan Ultra-Short Municipal Income ETF"},
     {"ticker": "AMOV", "name": "American Movil"},
     {"ticker": "AMP", "name": "Ameriprise"},
     {"ticker": "AMT", "name": "American Tower"},
     {"ticker": "AMTX", "name": "Aemetis Inc"},
     {"ticker": "AMX", "name": "America Movil"},
     {"ticker": "AMZN", "name": "Amazon"},
     {"ticker": "ANET", "name": "Arista"},
     {"ticker": "ANSS", "name": "ANSYS"},
     {"ticker": "ANTM", "name": "Anthem"},
     {"ticker": "AON", "name": "Aon"},
     {"ticker": "APD", "name": "Air Products and Chemicals"},
     {"ticker": "APH", "name": "Amphenol"},
     {"ticker": "APP", "name": "Applovin"},
     {"ticker": "APTV", "name": "Aptiv"},
     {"ticker": "ARE", "name": "Alecandria Real Estate Equities"},
     {"ticker": "ARKK", "name": "ARK Innovation ETF"},
     {"ticker": "ARPO", "name": "Aerpio Pharmaceuticals"},
     {"ticker": "ASML", "name": "ASML Holding"},
     {"ticker": "ASXC", "name": "Asensus Surgical"},
     {"ticker": "ATUS", "name": "Atlice USA"},
     {"ticker": "ATVI", "name": "Activision Blizzard"},
     {"ticker": "AVB", "name": "AvalonBay"},
     {"ticker": "AVGO", "name": "Broadcom"},
     {"ticker": "AVTR", "name": "Avantor"},
     {"ticker": "AVY", "name": "Avery Dennison"},
     {"ticker": "AWK", "name": "American Water Works"},
     {"ticker": "AXP", "name": "American Express"},
     {"ticker": "AZN", "name": "AstraZeneca"},
     {"ticker": "AZO", "name": "AutoZone"},
     {"ticker": "BA", "name": "Boeing"},
     {"ticker": "BABA", "name": "Alibaba"},
     {"ticker": "BAC", "name": "Bank of America"},
     {"ticker": "BAM", "name": "Brookfield Asset Management"},
     {"ticker": "BAX", "name": "Baxter"},
     {"ticker": "BB", "name": "Blackberry"},
     {"ticker": "BBBY", "name": "Bed Bath & Beyond"},
     {"ticker": "BBD", "name": "Banco Bradesco"},
     {"ticker": "BBDO", "name": "Banco Bradesco"},
     {"ticker": "BBL", "name": "BHP Group"},
     {"ticker": "BBVA", "name": "Banco Bilbao"},
     {"ticker": "BBY", "name": "Best Buy"},
     {"ticker": "BCE", "name": "BCE"},
     {"ticker": "BCS", "name": "Barclays"},
     {"ticker": "BDX", "name": "Becton, Dickinson & Company"},
     {"ticker": "BEKE", "name": "KE Holdings"},
     {"ticker": "BEN", "name": "Franklin Resources"},
     {"ticker": "BGFV", "name": "Big 5"},
     {"ticker": "BGNE", "name": "BeiGene"},
     {"ticker": "BHP", "name": "BHP Group"},
     {"ticker": "BIDU", "name": "Baidu"},
     {"ticker": "BIIB", "name": "Biogen"},
     {"ticker": "BILI", "name": "Bilibili"},
     {"ticker": "BIO", "name": "Bio-Rad Laboratories"},
     {"ticker": "BIP", "name": "Brookfield Infastructure Partners"},
     {"ticker": "BK", "name": "The Bank of New York Mellon"},
     {"ticker": "BKNG", "name": "Booking Holdings"},
     {"ticker": "BKR", "name": "Baker Hughes"},
     {"ticker": "BLK", "name": "BlackRock"},
     {"ticker": "BLL", "name": "Ball"},
     {"ticker": "BLNK", "name": "Blink Charging"},
     {"ticker": "BLUE", "name": "Bluebird bio"},
     {"ticker": "BMBL", "name": "Bumble"},
     {"ticker": "BMO", "name": "Bank of Montreal"},
     {"ticker": "BMRN", "name": "BioMarin"},
    {"ticker": "BMWYY", "name": "BMW"},
     {"ticker": "BMY", "name": "Bristol-Myers Squibb"},
     {"ticker": "BNGO", "name": "Bionano Genomics"},
     {"ticker": "BNS", "name": "Bank of Nova Scotia"},
     {"ticker": "BNTX", "name": "BioNTech"},
     {"ticker": "BP", "name": "BP plc"},
     {"ticker": "BPY", "name": "Brookfield Property Partners"},
     {"ticker": "BR", "name": "Broadridge Financial Solutions"},
     {"ticker": "BRK.A", "name": "Berkshire Hathaway"},
     {"ticker": "BRK.B", "name": "Berkshire Hathaway"},
     {"ticker": "BSBR", "name": "Banco Santander Brasil"},
     {"ticker": "BSX", "name": "Boston Scientific"},
     {"ticker": "BSY", "name": "Bently Systems"},
     {"ticker": "BTI", "name": "British American Tobacco Industry"},
     {"ticker": "BUD", "name": "Anheuser-Busch Inbev"},
     {"ticker": "BURL", "name": "Burlington Stores"},
     {"ticker": "BX", "name": "The Blackstone Group"},
     {"ticker": "BXP", "name": "Boston Properties"},
    {"ticker": "BYDDY", "name": "BYD Company"},
     {"ticker": "BYND", "name": "Beyond Meat"},
     {"ticker": "C", "name": "Citigroup"},
     {"ticker": "CAG", "name": "ConAgra Brands"},
     {"ticker": "CAH", "name": "Cardinal Health"},
     {"ticker": "CAJ", "name": "Canon"},
     {"ticker": "CARR", "name": "Carrier Global"},
     {"ticker": "CAT", "name": "Caterpillar"},
     {"ticker": "CB", "name": "Chubb Limited"},
     {"ticker": "CBRE", "name": "CBRE"},
     {"ticker": "CCEP", "name": "Coca-Cola Europacific Partners"},
     {"ticker": "CCI", "name": "Crown Castle International"},
     {"ticker": "CCIV", "name": "Churchill Capital"},
     {"ticker": "CCL", "name": "Carnival"},
     {"ticker": "CDNS", "name": "Cadence Design Systems"},
     {"ticker": "CDW", "name": "CDW Corp"},
     {"ticker": "CE", "name": "Celanese"},
     {"ticker": "CERN", "name": "Cerner"},
     {"ticker": "CFG", "name": "Citizens Financial Group"},
     {"ticker": "CG", "name": "Carlyle Group"},
     {"ticker": "CGC", "name": "Canopy Growth"},
     {"ticker": "CHD", "name": "Church & Dwight"},
     {"ticker": "CHKP", "name": "Check Point Software"},
     {"ticker": "CHPT", "name": "ChargePoint"},
     {"ticker": "CHT", "name": "Chunghwa Telecom"},
     {"ticker": "CHTR", "name": "Charter Communications"},
     {"ticker": "CHWY", "name": "Chewy"},
     {"ticker": "CI", "name": "Cigna"},
     {"ticker": "CINF", "name": "Cincinatti Financial Corp"},
     {"ticker": "CL", "name": "Colgate"},
     {"ticker": "CLVT", "name": "Clarivate"},
     {"ticker": "CLX", "name": "Clorox"},
     {"ticker": "CM", "name": "Canadian Imperial Bank of Commerce"},
   {"ticker": "CMCSA", "name": "Comcast"},
     {"ticker": "CME", "name": "CME Group"},
     {"ticker": "CMG", "name": "Chipotle"},
     {"ticker": "CMI", "name": "Cummins"},
     {"ticker": "CMS", "name": "CMS Energy"},
     {"ticker": "CNC", "name": "Centene"},
     {"ticker": "CNHI", "name": "CHN Industrial"},
     {"ticker": "CNI", "name": "Canadian National Railway"},
     {"ticker": "CNP", "name": "CenterPoint Energy"},
     {"ticker": "CNQ", "name": "Canadian Natural Resources"},
     {"ticker": "COF", "name": "Capital One Financial"},
     {"ticker": "COIN", "name": "Coinbase"},
     {"ticker": "COO", "name": "Cooper Companies"},
     {"ticker": "COP", "name": "ConocoPhillips"},
     {"ticker": "COST", "name": "Costco Wholesale"},
     {"ticker": "COUP", "name": "Coupa Software Inc"},
     {"ticker": "CP", "name": "Canadian Pacific Railway"},
     {"ticker": "CPNG", "name": "Coupang"},
     {"ticker": "CPRT", "name": "Copart"},
     {"ticker": "CPRX", "name": "Catalyst Pharmaceuticals"},
     {"ticker": "CQP", "name": "Cheniere Energy Partners"},
     {"ticker": "CRBP", "name": "Corbus Pharmaceuticals"},
     {"ticker": "CRH", "name": "CRH"},
     {"ticker": "CRL", "name": "Charlers River Laboratories"},
     {"ticker": "CRM", "name": "Salesforce"},
     {"ticker": "CRON", "name": "Cronos Group"},
     {"ticker": "CRWD", "name": "CrowdStrike"},
     {"ticker": "CS", "name": "Credit Suisse"},
     {"ticker": "CSAN", "name": "Cosan"},
     {"ticker": "CSCO", "name": "Cisco"},
     {"ticker": "CSGP", "name": "CoStar Group"},
     {"ticker": "CSX", "name": "CSX Corporation"},
     {"ticker": "CTAS", "name": "Cintas"},
     {"ticker": "CTLT", "name": "Catalent"},
     {"ticker": "CTSH", "name": "Cognizant"},
     {"ticker": "CTVA", "name": "Corteva"},
     {"ticker": "CUK", "name": "Carnival"},
     {"ticker": "CVAC", "name": "CureVac"},
     {"ticker": "CVE", "name": "Cenovus Energy"},
     {"ticker": "CVNA", "name": "Carvano"},
     {"ticker": "CVS", "name": "CVS Health"},
     {"ticker": "CVX", "name": "Chevron"},
     {"ticker": "CYRX", "name": "CryoPort"},
     {"ticker": "CZR", "name": "Caesars Entertainment"},
     {"ticker": "D", "name": "Doiminion Energy"},
     {"ticker": "DAC", "name": "Danaos Corp"},
     {"ticker": "DAL", "name": "Delta Air Lines"},
     {"ticker": "DASH", "name": "DoorDash"},
     {"ticker": "DB", "name": "Deutsche Bank"},
     {"ticker": "DD", "name": "DuPont de Nemours"},
     {"ticker": "DDOG", "name": "Datadog"},
     {"ticker": "DE", "name": "Deere & Company"},
     {"ticker": "DELL", "name": "Dell"},
     {"ticker": "DEO", "name": "Diaegeo"},
     {"ticker": "DFS", "name": "Discover"},
     {"ticker": "DG", "name": "Dollar General"},
     {"ticker": "DGX", "name": "Quest Diagnostics"},
     {"ticker": "DHI", "name": "D.R. Horton"},
     {"ticker": "DHR", "name": "Danaher"},
     {"ticker": "DIS", "name": "Disney"},
   {"ticker": "DISCA", "name": "Discovery"},
   {"ticker": "DISCB", "name": "Discovery"},
   {"ticker": "DISCK", "name": "Discovery"},
     {"ticker": "DISH", "name": "DISH Network"},
     {"ticker": "DIT", "name": "Amcon Distributing"},
     {"ticker": "DKNG", "name": "DraftKings"},
     {"ticker": "DLR", "name": "Digital Realty Trust"},
     {"ticker": "DLTR", "name": "Dollar Tree"},
     {"ticker": "DOCU", "name": "DocuSign"},
     {"ticker": "DOV", "name": "Dover"},
     {"ticker": "DOW", "name": "Dow"},
     {"ticker": "DPZ", "name": "Domino's Pizza"},
     {"ticker": "DRE", "name": "Duke Realty"},
     {"ticker": "DRI", "name": "Darden Restaurants"},
     {"ticker": "DT", "name": "Dynatrace"},
     {"ticker": "DVN", "name": "Devon Energy"},
     {"ticker": "DXCM", "name": "DexCom"},
     {"ticker": "E", "name": "Eni"},
     {"ticker": "EA", "name": "Electronic Artis"},
     {"ticker": "EC", "name": "Ecopetrol"},
     {"ticker": "ECL", "name": "Ecolab"},
     {"ticker": "ED", "name": "Consolidated Edison"},
     {"ticker": "EDU", "name": "New Oriential Education & Technology"},
     {"ticker": "EFX", "name": "Equifax"},
     {"ticker": "EHTH", "name": "eHealth"},
     {"ticker": "EIX", "name": "Edison International"},
     {"ticker": "EL", "name": "Estee Lauder"},
     {"ticker": "ELAN", "name": "Elanco Animal Health"},
     {"ticker": "ELP", "name": "Paranaense de Energia"},
     {"ticker": "EMB", "name": "iShares JP Morgan USD Emerging Markets Bond ETF"},
     {"ticker": "EMN", "name": "Eastman Chemical"},
     {"ticker": "EMR", "name": "Emerson Electric"},
     {"ticker": "ENPH", "name": "Enphase Energy"},
     {"ticker": "ENTG", "name": "Entegris"},
     {"ticker": "EOG", "name": "EOG Resources"},
     {"ticker": "EPAM", "name": "EPAM"},
     {"ticker": "EPD", "name": "Enterprise Products"},
     {"ticker": "EPIX", "name": "Essa Pharma"},
     {"ticker": "EQIX", "name": "Equinix"},
     {"ticker": "EQNR", "name": "Equinor"},
     {"ticker": "EQR", "name": "Equity Residential"},
     {"ticker": "ERIC", "name": "Ericsson"},
     {"ticker": "ES", "name": "Eversource Energy"},
     {"ticker": "ESS", "name": "Essex Property Trust"},
     {"ticker": "ET", "name": "Energy Transfer"},
     {"ticker": "ETN", "name": "Eaton"},
     {"ticker": "ETR", "name": "Entergy"},
     {"ticker": "ETSY", "name": "Etsy"},
     {"ticker": "EW", "name": "Edwards Lifesciences"},
     {"ticker": "EXAS", "name": "Exact Sciences"},
     {"ticker": "EXC", "name": "Exelon"},
     {"ticker": "EXPD", "name": "Expeditors International of Washington"},
     {"ticker": "EXPE", "name": "Expedia"},
     {"ticker": "EXPR", "name": "Express"},
     {"ticker": "EXR", "name": "Extra Space Storage"},
     {"ticker": "F", "name": "Ford Motor"},
     {"ticker": "FAST", "name": "Fastenal"},
     {"ticker": "FB", "name": "Facebook"},
     {"ticker": "FCEL", "name": "FuelCell Energy"},
     {"ticker": "FCX", "name": "Freeport-McMoRan"},
     {"ticker": "FDX", "name": "FedEx"},
     {"ticker": "FE", "name": "FirstEnergy"},
     {"ticker": "FERG", "name": "Ferguson"},
     {"ticker": "FIS", "name": "Fidelity"},
     {"ticker": "FISV", "name": "Fiserv"},
     {"ticker": "FITB", "name": "Fifth Third Bancorp"},
     {"ticker": "FLDM", "name": "Fluidigm"},
     {"ticker": "FLT", "name": "FleetCor"},
     {"ticker": "FMC", "name": "FMC Corp"},
     {"ticker": "FMS", "name": "Fresenius Medical Care"},
     {"ticker": "FMX", "name": "Fomento Economico Mexicano"},
     {"ticker": "FNV", "name": "Franco-Nevada"},
     {"ticker": "FOX", "name": "Fox Class B"},
     {"ticker": "FOXA", "name": "Fox Class A"},
     {"ticker": "FRC", "name": "FIRST REPUBLIC BANK"},
     {"ticker": "FSR", "name": "Fisker"},
     {"ticker": "FTCH", "name": "Farfetch Limited"},
     {"ticker": "FTNT", "name": "Fortinet"},
     {"ticker": "FTS", "name": "Fortis"},
     {"ticker": "FTV", "name": "Fortive"},
         {"ticker": "FUBO", "name": "Fubo"},
         {"ticker": "FUTU", "name": "Futu Holdings"},
         {"ticker": "FVRR", "name": "Fiverr"},
           {"ticker": "GD", "name": "General Dynamics"},
         {"ticker": "GDRX", "name": "GoodRx"},
           {"ticker": "GE", "name": "General Electric"},
           {"ticker": "GH", "name": "Guardant Health"},
           {"ticker": "GIB", "name": "CGI"},
            {"ticker": "GILD", "name": "Gilead Sciences"},
           {"ticker": "GIS", "name": "General Mills"},
           {"ticker": "GLW", "name": "Corning"},
             {"ticker": "GM", "name": "General Motors"},
             {"ticker": "GMAB", "name": "Genmab"},
               {"ticker": "GME", "name": "GameStop"},
         {"ticker": "GNRC", "name": "Generac Holdings"},
         {"ticker": "GNUS", "name": "Genius Brands"},
         {"ticker": "GOLD", "name": "Barrick Gold"},
         {"ticker": "GOOG", "name": "Alphabet Class C"},
        {"ticker": "GOOGL", "name": "Alphabet Class A"},
          {"ticker": "GOOS", "name": "Canada Goose"},
         {"ticker": "GPC", "name": "Genuine Parts"},
         {"ticker": "GPN", "name": "Globaal Payments"},
          {"ticker": "GPRO", "name": "GoPro"},
          {"ticker": "GRMN", "name": "Garmin"},
         {"ticker": "GS", "name": "Goldman Sachs"},
          {"ticker": "GSAT", "name": "Globalstar"},
         {"ticker": "GSK", "name": "GlaxoSmithKline"},
          {"ticker": "GTIM", "name": "Good Times Rest"},
         {"ticker": "GWW", "name": "W.W. Grainger"},
         {"ticker": "HAL", "name": "Haliburton"},
          {"ticker": "HBAN", "name": "Huntington Bancshares"},
         {"ticker": "HCA", "name": "HCA HealthCare"},
       {"ticker": "HD", "name": "Home Depot"},
         {"ticker": "HDB", "name": "HDFC Bank"},
         {"ticker": "HEI", "name": "Heico"},
         {"ticker": "HES", "name": "HESS"},
          {"ticker": "HEXO", "name": "HEXO"},
         {"ticker": "HIG", "name": "Hartford Financial Services Group"},
         {"ticker": "HLT", "name": "Hilton Worldwide Holdings"},
         {"ticker": "HMC", "name": "Honda"},
          {"ticker": "HOLX", "name": "Hologic"},
         {"ticker": "HON", "name": "Honeywell"},
         {"ticker": "HPE", "name": "Hewlett Packard"},
         {"ticker": "HPQ", "name": "HP"},
         {"ticker": "HRL", "name": "Hormel Foods"},
          {"ticker": "HSBC", "name": "HSBC Holdings"},
         {"ticker": "HSY", "name": "Hershey"},
          {"ticker": "HTHT", "name": "Huazhu Group"},
          {"ticker": "HUBS", "name": "HubSpot"},
         {"ticker": "HUM", "name": "Humana"},
         {"ticker": "HWM", "name": "Howmet Aerospace"},
          {"ticker": "HZNP", "name": "Horizon Therapeutics"},
         {"ticker": "IAC", "name": "IAC"},
          {"ticker": "IBIO", "name": "iBio"},
          {"ticker": "IBKR", "name": "Interactive Brokers Group"},
         {"ticker": "IBM", "name": "International Business Machines"},
         {"ticker": "IBN", "name": "ICICI Bank"},
         {"ticker": "ICE", "name": "Intercontinental Exchange"},
          {"ticker": "IDEX", "name": "Ideanomics"},
          {"ticker": "IDXX", "name": "IDEXX Laboratories"},
         {"ticker": "IEX", "name": "IDEX"},
         {"ticker": "IFF", "name": "International Flavors & Fragrances"},
          {"ticker": "ILMN", "name": "Illumina"},
         {"ticker": "IMO", "name": "Imperial Oil"},
          {"ticker": "INCY", "name": "Incyte"},
          {"ticker": "INFO", "name": "IHS Markit"},
          {"ticker": "INFY", "name": "Infosys"},
         {"ticker": "ING", "name": "ING"},
         {"ticker": "INO", "name": "Inovio"},
          {"ticker": "INPX", "name": "Inpixon"},
          {"ticker": "INTC", "name": "Intel"},
          {"ticker": "INTU", "name": "Intuit"},
          {"ticker": "INVH", "name": "Invitation Homes"},
         {"ticker": "IP", "name": "international Paper Company"},
         {"ticker": "IQV", "name": "IQVIA Holdings"},
         {"ticker": "IR", "name": "Ingersoll Rand"},
         {"ticker": "IRBT", "name": "iRobot"},
         {"ticker": "ISRG", "name": "Intuitive Surgical"},
         {"ticker": "IT", "name": "Gartner"},
          {"ticker": "ITUB", "name": "Itau Unibanco"},
          {"ticker": "ITW", "name": "Illinois Tools Works"},
          {"ticker": "IVR", "name": "Invesco Mortgage Capital"},
          {"ticker": "IX", "name": "Orix"},
         {"ticker": "J", "name": "Jacobs Engineering Group"},
           {"ticker": "JBHT", "name": "J.B. Hunt Transport Services"},
           {"ticker": "JBLU", "name": "JetBlue Airways"},
         {"ticker": "JCI", "name": "Johnson Controls International"},
         {"ticker": "JD", "name": "JD.com"},
         {"ticker": "JNJ", "name": "Johnson & Johnson"},
         {"ticker": "JPM", "name": "JPMorgan Chase"},
           {"ticker": "JPST", "name": "JPMorgan Ultra-Short Income ETF"},
       {"ticker": "K", "name": "Kellogg"},
         {"ticker": "KB", "name": "KB Financial"},
         {"ticker": "KDP", "name": "Keurig Dr Pepper"},
         {"ticker": "KEP", "name": "Korea Electric power"},
         {"ticker": "KEY", "name": "KeyCorp"},
           {"ticker": "KEYS", "name": "Keysight Technologies"},
         {"ticker": "KHC", "name": "Kraft Foods"},
           {"ticker": "KIRK", "name": "Kirkland's"},
         {"ticker": "KKR", "name": "KKR"},
           {"ticker": "KLAC", "name": "KLA"},
         {"ticker": "KMB", "name": "Kimberly-Clark"},
         {"ticker": "KMI", "name": "Kinder Morgan"},
         {"ticker": "KMX", "name": "CarMax"},
         {"ticker": "KO", "name": "Coca-Cola"},
         {"ticker": "KR", "name": "Kroger"},
           {"ticker": "KSU", "name": "Kansas City Southern"},
         {"ticker": "L", "name": "Loews"},
           {"ticker": "LB", "name": "L Brands"},
           {"ticker": "LBRDA", "name": "Liberty Broadband"},
           {"ticker": "LBRDK", "name": "Liberty Broadband"},
           {"ticker": "LBTYA", "name": "Liberty Global"},
           {"ticker": "LBTYK", "name": "Liberty Global"},
             {"ticker": "LCRX", "name": "Lam Research"},
             {"ticker": "LEN", "name": "Lennar"},
             {"ticker": "LFC", "name": "China Life Insurance"},
           {"ticker": "LH", "name": "LabCorp"},
            {"ticker": "LHX", "name": "L3Harris"},
           {"ticker": "LI", "name": "Li Auto"},
            {"ticker": "LIN", "name": "Linde"},
            {"ticker": "LLY", "name": "Eli Lilly"},
            {"ticker": "LMT", "name": "Lockheed Martin"},
            {"ticker": "LNG", "name": "Cheniere Energy"},
            {"ticker": "LOB", "name": "Live Oak Bansch"},
                 {"ticker": "LOGI", "name": "Logitech"},
               {"ticker": "LOW", "name": "Lowe's"},
                 {"ticker": "LPCN", "name": "Lipocine"},
               {"ticker": "LSXMA", "name": "Liberty Media"},
               {"ticker": "LSXMB", "name": "Liberty Media"},
               {"ticker": "LU", "name": "Lufax"},
                 {"ticker": "LULU", "name": "Lululemon Athletica"},
               {"ticker": "LUV", "name": "Southwest Airlines"},
               {"ticker": "LVS", "name": "Las Vegas Sands"},
               {"ticker": "LYB", "name": "LyondelBassel"},
                 {"ticker": "LYFT", "name": "Lyft"},
               {"ticker": "LYG", "name": "Lloyds Banking"},
               {"ticker": "LYV", "name": "Live Nation Entertainment"},
             {"ticker": "M", "name": "Macy's"},
              {"ticker": "MA", "name": "Mastercard"},
               {"ticker": "MAA", "name": "Mid-America Apartment Communities"},
               {"ticker": "MAR", "name": "Mariott"},
               {"ticker": "MCD", "name": "McDonald's"},
               {"ticker": "MCHP", "name": "Microchip Technology"},
              {"ticker": "MCK", "name": "McKesson"},
              {"ticker": "MCO", "name": "Moody's"},
              {"ticker": "MDB", "name": "MongoDB"},
               {"ticker": "MDLZ", "name": "Mondelez International"},
              {"ticker": "MDT", "name": "Medtronic"},
               {"ticker": "MELI", "name": "MercadoLibre"},
              {"ticker": "MET", "name": "MetLife"},
              {"ticker": "MFC", "name": "Manulife"},
              {"ticker": "MFG", "name": "Mizuho"},
              {"ticker": "MGA", "name": "Magna"},
              {"ticker": "MGM", "name": "MGM Resorts"},
              {"ticker": "MHK", "name": "Mohawk Industries"},
              {"ticker": "MKC", "name": "McCormick & Company"},
              {"ticker": "MKL", "name": "Markel"},
          {"ticker": "MKTX", "name": "MarketAxess"},
         {"ticker": "MLM", "name": "Martin Marietta Materials"},
         {"ticker": "MMC", "name": "Marsh & McLennan"},
         {"ticker": "MMM", "name": "3M"},
          {"ticker": "MNST", "name": "Monster"},
           {"ticker": "MO", "name": "Altria"},
         {"ticker": "MOH", "name": "Molina Healthcare"},
         {"ticker": "MPC", "name": "Marathon Petroleum"},
          {"ticker": "MPLX", "name": "MPLX LP"},
          {"ticker": "MPWR", "name": "Monolithic Power Systems"},
         {"ticker": "MRK", "name": "Merck"},
          {"ticker": "MRNA", "name": "Moderna"},
         {"ticker": "MRO", "name": "Marathon Oil"},
          {"ticker": "MRVL", "name": "Marvell Tecnhology"},
          {"ticker": "MS", "name": "Morgan Stanley"},
          {"ticker": "MSCI", "name": "MSCI"},
          {"ticker": "MSFT", "name": "Microsoft"},
         {"ticker": "MSI", "name": "Motorola Solutions"},
           {"ticker": "MT", "name": "Arcelor Mittal"},
         {"ticker": "MTB", "name": "M&T Bank"},
          {"ticker": "MTCH", "name": "Match"},
         {"ticker": "MTD", "name": "Mettler-Toledo"},
             {"ticker": "MU", "name": "Micron"},
          {"ticker": "MUFG", "name": "Mitsubishi"},
          {"ticker": "MVIS", "name": "MicroVision"},
          {"ticker": "MXIM", "name": "Maxim Integrated"},
          {"ticker": "NAKD", "name": "Naked Brand"},
          {"ticker": "NCLH", "name": "Norwegian Cruise Line"},
          {"ticker": "NDAQ", "name": "Nasdaq"},
         {"ticker": "NEE", "name": "NextEra Energy"},
         {"ticker": "NET", "name": "Cloudflare"},
          {"ticker": "NFLX", "name": "Netflix"},
         {"ticker": "NGG", "name": "National Grid Transco"},
         {"ticker": "NIO", "name": "Nio"},
         {"ticker": "NKE", "name": "Nike"},
          {"ticker": "NKLA", "name": "Nikola"},
          {"ticker": "NLOK", "name": "NortonLifeLock"},
         {"ticker": "NMR", "name": "Nomura Holdings"},
          {"ticker": "NNDM", "name": "Nano Dimension"},
         {"ticker": "NOC", "name": "Northrop Grumman"},
         {"ticker": "NOK", "name": "Nokia"},
          {"ticker": "NOVA", "name": "Sunnova Energy"},
         {"ticker": "NOW", "name": "ServiceNow"},
         {"ticker": "NRZ", "name": "New Residential Invesment"},
         {"ticker": "NSC", "name": "Norfolk Southern Corporation"},
          {"ticker": "NTAP", "name": "NetApp"},
          {"ticker": "NTES", "name": "NetEase"},
         {"ticker": "NTR", "name": "Nutrien"},
          {"ticker": "NTRS", "name": "Northern Trust"},
         {"ticker": "NUE", "name": "Nucor"},
          {"ticker": "NVCR", "name": "NovoCure"},
          {"ticker": "NVDA", "name": "NVIDIA"},
         {"ticker": "NVO", "name": "Novo Nordisk"},
         {"ticker": "NVR", "name": "NVR"},
         {"ticker": "NVS", "name": "Novartis AG"},
         {"ticker": "NWG", "name": "NatWest"},
          {"ticker": "NWSA", "name": "News Corp"},
          {"ticker": "NXPI", "name": "NXP Semiconductors"},
           {"ticker": "O", "name": "Realty Income"},
          {"ticker": "OCGN", "name": "Ocugen"},
          {"ticker": "ODFL", "name": "Old Dominion Freight Line"},
         {"ticker": "OGI", "name": "OrganiGram"},
         {"ticker": "OKE", "name": "ONEOK"},
          {"ticker": "OKTA", "name": "Okta"},
         {"ticker": "OMC", "name": "Omnicom"},
           {"ticker": "ON", "name": "ON Semiconductor"},
          {"ticker": "ORAN", "name": "Orange"},
          {"ticker": "ORCL", "name": "Oracle"},
          {"ticker": "ORLY", "name": "O'Reilly"},
          {"ticker": "OTIS", "name": "Otis"},
          {"ticker": "OTLK", "name": "Outlook Therapeutics"},
          {"ticker": "OVID", "name": "Ovid Therapeutics"},
         {"ticker": "OXY", "name": "Occidental Petroleum"},
          {"ticker": "PAAS", "name": "Pan American Silver"},
          {"ticker": "PAGS", "name": "PagSeguro Digital"},
          {"ticker": "PANW", "name": "Palo Alto Networks"},
          {"ticker": "PATH", "name": "UiPath"},
          {"ticker": "PAYC", "name": "Paycom Software"},
          {"ticker": "PAYX", "name": "Paychex"},
         {"ticker": "PBA", "name": "Pembina Pipeline"},
         {"ticker": "PBR", "name": "Petroleo Brasileiro"},
          {"ticker": "PCAR", "name": "PACCAR"},
         {"ticker": "PCG", "name": "Pacific Gas & Electric"},
          {"ticker": "PEAK", "name": "Healthpeak Properties"},
         {"ticker": "PEG", "name": "Public Service Enterprise"},
          {"ticker": "PENN", "name": "Penn National Gambling"},
         {"ticker": "PEP", "name": "Pepsi"},
         {"ticker": "PFE", "name": "Pfizer"},
         {"ticker": "PFG", "name": "principal Financial Group"},
         {"ticker": "PG", "name": "Procter & Gamble"},
         {"ticker": "PGR", "name": "Progressive"},
           {"ticker": "PH", "name": "Parker-Hannifin"},
         {"ticker": "PHG", "name": "Royal Philips"},
          {"ticker": "PINS", "name": "Pinterest"},
         {"ticker": "PKI", "name": "PerkinElmer"},
         {"ticker": "PKX", "name": "POSCO"},
          {"ticker": "PLAY", "name": "Dave & Buster's"},
         {"ticker": "PLD", "name": "Prologis"},
          {"ticker": "PLTR", "name": "Palantir Technologies"},
          {"ticker": "PLUG", "name": "Plug Power"},
           {"ticker": "PM", "name": "Philip Morris"},
         {"ticker": "PNC", "name": "PNC Financial Services Group"},
          {"ticker": "PODD", "name": "Insulet"},
          {"ticker": "POOL", "name": "Pool Corp"},
          {"ticker": "POSH", "name": "Poshmark"},
         {"ticker": "PPD", "name": "PPD"},
         {"ticker": "PPG", "name": "PPG"},
         {"ticker": "PPL", "name": "PPL"},
         {"ticker": "PRU", "name": "Prudential Financial"},
         {"ticker": "PSA", "name": "Public Storage"},
          {"ticker": "PSEC", "name": "Prospect Capital"},
         {"ticker": "PSX", "name": "Phillips 66"},
         {"ticker": "PTC", "name": "PTC"},
          {"ticker": "PTON", "name": "Peloton"},
         {"ticker": "PTR", "name": "PetroChina"},
         {"ticker": "PUK", "name": "Prudential Public"},
         {"ticker": "PXD", "name": "Pioneer"},
          {"ticker": "PYPL", "name": "PayPal"},
          {"ticker": "QCOM", "name": "QUALCOMM"},
          {"ticker": "QRVO", "name": "Qorvo"},
         {"ticker": "QSR", "name": "Restaurant Brands"},
          {"ticker": "RACE", "name": "Ferrari"},
          {"ticker": "RBLX", "name": "Roblox"},
         {"ticker": "RCI", "name": "Rogers Communication"},
         {"ticker": "RCL", "name": "Royal Caribbean Group"},
          {"ticker": "RDFN", "name": "Redfin"},
          {"ticker": "Real", "name": "The RealReal"},
          {"ticker": "REGN", "name": "Regeneron Pharmaceuticals"},
          {"ticker": "RELX", "name": "RELX"},
           {"ticker": "RF", "name": "Regions Financial"},
         {"ticker": "RIO", "name": "Rio Tinto"},
          {"ticker": "RIOT", "name": "Riot Blockchain"},
         {"ticker": "RJF", "name": "Raymond James Financial"},
         {"ticker": "RLX", "name": "RLX Technology"},
         {"ticker": "RMD", "name": "ResMed"},
         {"ticker": "RNG", "name": "RingCentral"},
         {"ticker": "ROK", "name": "Rockwell Automation"},
          {"ticker": "ROKU", "name": "Roku"},
         {"ticker": "ROL", "name": "Rollins"},
         {"ticker": "ROP", "name": "Roper"},
          {"ticker": "ROST", "name": "Ross"},
          {"ticker": "RPRX", "name": "Royalty Pharma"},
         {"ticker": "RSG", "name": "Reupublic Services"},
         {"ticker": "RTX", "name": "Raytheon Technologies"},
         {"ticker": "RY", "name": "Royal Bank of Canada"},
          {"ticker": "RYAAY", "name": "Ryanair Holdings"},
          {"ticker": "RYCEY", "name": "Rolls-Royce"},
         {"ticker": "SAN", "name": "Banco Santander"},
         {"ticker": "SAP", "name": "SAP SE"},
          {"ticker": "SAVE", "name": "Spirit Airlines"},
          {"ticker": "SBAC", "name": "SBA Communications"},
          {"ticker": "SBUX", "name": "Starbucks"},
          {"ticker": "SCCO", "name": "Southern Copper"},
          {"ticker": "SCHW", "name": "Charles Schwab"},
           {"ticker": "SE", "name": "Sea Limited AMerican Depositary Shares"},
          {"ticker": "SENS", "name": "Senseonics"},
          {"ticker": "SGEN", "name": "Seagen"},
         {"ticker": "SHG", "name": "Shinhan Financial Group"},
          {"ticker": "SHOP", "name": "Shopify"},
         {"ticker": "SHW", "name": "Sherwin-Williams"},
          {"ticker": "SIRI", "name": "Sirius XM"},
          {"ticker": "SIVB", "name": "SVB"},
         {"ticker": "SKM", "name": "SK Telecom"},
         {"ticker": "SLB", "name": "Schlumberger"},
         {"ticker": "SLF", "name": "Sun Life"},
         {"ticker": "SLV", "name": "iShares Silver trust"},
          {"ticker": "SMFG", "name": "Sumitomo Mitsui"},
         {"ticker": "SNA", "name": "Snap-On"},
          {"ticker": "SNAP", "name": "Snap"},
          {"ticker": "SNDL", "name": "Sundial Growers"},
         {"ticker": "SNN", "name": "Smith & Nephew"},
          {"ticker": "SNOW", "name": "Snowflake"},
         {"ticker": "SNP", "name": "China Petroleum & Chemical Corporation"},
          {"ticker": "SNPS", "name": "Synopsys"},
         {"ticker": "SNY", "name": "Sanofi"},
           {"ticker": "SO", "name": "Southern Company"},
          {"ticker": "SONY", "name": "Sony"},
         {"ticker": "SOS", "name": "SOS Limited"},
          {"ticker": "SPCE", "name": "Virgin Galactic Holdings"},
         {"ticker": "SPG", "name": "Simon Property Group"},
          {"ticker": "SPGI", "name": "S&P Global"},
          {"ticker": "SPLK", "name": "Splunk"},
          {"ticker": "SPOT", "name": "Spotify"},
          {"ticker": "SPPI", "name": "Spectrum Pharmaceuticals"},
         {"ticker": "SPY", "name": "SPDR S&P 500 ETF"},
           {"ticker": "SQ", "name": "Square"},
         {"ticker": "SRE", "name": "Sempra Energy"},
          {"ticker": "SSNC", "name": "SS&C Technologies"},
         {"ticker": "STE", "name": "STERIS"},
          {"ticker": "STLA", "name": "Stellantis"},
         {"ticker": "STM", "name": "STMicroelectronics"},
          {"ticker": "STNE", "name": "StoneCo"},
         {"ticker": "STT", "name": "State Street"},
         {"ticker": "STX", "name": "Seagate Technology"},
         {"ticker": "STZ", "name": "Constellation Brands"},
         {"ticker": "SU", "name": "Suncor Energy"},
         {"ticker": "SUI", "name": "Sun Communities"},
         {"ticker": "SUZ", "name": "Suzano"},
         {"ticker": "SVM", "name": "Silvercorp Metals"},
         {"ticker": "SWK", "name": "Stanley Black & Decker"},
          {"ticker": "SWKS", "name": "Skyworks"},
         {"ticker": "SYF", "name": "Synchrony"},
         {"ticker": "SYK", "name": "Stryker"},
         {"ticker": "SYY", "name": "Sysco"},
           {"ticker": "T", "name": "AT&T"},
         {"ticker": "TAK", "name": "Takeda Pharmaceutical"},
         {"ticker": "TAL", "name": "TAL Education"},
          {"ticker": "TCOM", "name": "Trip.com"},
           {"ticker": "TD", "name": "Toronto Dominion Bank"},
         {"ticker": "TDG", "name": "Transdigm"},
          {"ticker": "TDOC", "name": "Teladoc Health"},
         {"ticker": "TDY", "name": "Teledyne"},
          {"ticker": "TEAM", "name": "Atlassian"},
          {"ticker": "TECH", "name": "Bio-Techne"},
         {"ticker": "TEF", "name": "Telefonica"},
         {"ticker": "TEL", "name": "TE Connectivity"},
         {"ticker": "TER", "name": "Teradyne"},
         {"ticker": "TFC", "name": "Truist Financial"},
         {"ticker": "TFX", "name": "Teleflex"},
         {"ticker": "TGT", "name": "Target"},
         {"ticker": "TJX", "name": "TJX Companies"},
         {"ticker": "TLK", "name": "PT Telekommunikasi Indonesia"},
          {"ticker": "TLRY", "name": "Tilray"},
           {"ticker": "TM", "name": "Toyota"},
         {"ticker": "TME", "name": "Tencent Music Entertainment"},
         {"ticker": "TMO", "name": "Thermo Fisher Scientific"},
          {"ticker": "TMUS", "name": "T-Mobile"},
          {"ticker": "TNXP", "name": "Tonix Pharmaceuticals"},
         {"ticker": "TOT", "name": "Total"},
          {"ticker": "TRCH", "name": "Torchlight Energy Resources"},
         {"ticker": "TRI", "name": "Thomson Reuters"},
          {"ticker": "TRMB", "name": "Trimble"},
          {"ticker": "TROW", "name": "T.Rowe Price"},
         {"ticker": "TRP", "name": "TC Energy"},
         {"ticker": "TRU", "name": "TransUnion"},
         {"ticker": "TRV", "name": "Travelers"},
          {"ticker": "TSCO", "name": "Tractor Supply"},
          {"ticker": "TSLA", "name": "Tesla"},
         {"ticker": "TSM", "name": "Taiwan Semiconductor Manufacturing"},
         {"ticker": "TSN", "name": "Tyson Foods"},
         {"ticker": "TTD", "name": "The Trade Desk"},
          {"ticker": "TTWO", "name": "Take-Two Interactive Software"},
           {"ticker": "TU", "name": "Telus"},
           {"ticker": "TW", "name": "Tradeweb Markets"},
          {"ticker": "TWLO", "name": "Twilio"},
          {"ticker": "TWTR", "name": "Twitter"},
         {"ticker": "TXG", "name": "10x Genomics"},
          {"ticker": "TXMD", "name": "TherapeuticsMD"},
         {"ticker": "TXN", "name": "Texas Instruments"},
         {"ticker": "TXT", "name": "Textron"},
         {"ticker": "TYL", "name": "Tyler Technologies"},
           {"ticker": "U", "name": "Unity Software"},
           {"ticker": "UA", "name": "Under Armour"},
         {"ticker": "UAL", "name": "United Airlines"},
          {"ticker": "UBER", "name": "Uber"},
         {"ticker": "UBS", "name": "UBS Group"},
           {"ticker": "UI", "name": "Ubiquiti"},
         {"ticker": "UL", "name": "Unilever PLC"},
          {"ticker": "ULTA", "name": "Ulta Beauty"},
         {"ticker": "UMC", "name": "United Microelectronics"},
         {"ticker": "UNH", "name": "UnitedHealth"},
         {"ticker": "UNP", "name": "Union Pacific"},
         {"ticker": "UPS", "name": "United Parcel Service"},
          {"ticker": "UPWK", "name": "Upwork"},
         {"ticker": "URI", "name": "United Rentals"},
         {"ticker": "USB", "name": "US Bank"},
         {"ticker": "V", "name": "Visa"},
          {"ticker": "VALE", "name": "Vale"},
          {"ticker": "VEEV", "name": "Veeva Systems"},
         {"ticker": "VFC", "name": "V.F. Corporation"},
          {"ticker": "VIAC", "name": "ViacomCBS Class B"},
          {"ticker": "VIACA", "name": "ViacomCBS Class A"},
          {"ticker": "VICI", "name": "VICI Properties"},
          {"ticker": "VIPS", "name": "Vipshop Holdings"},
         {"ticker": "VLO", "name": "Valero Energy"},
         {"ticker": "VMC", "name": "Vulcan Materials"},
         {"ticker": "VMW", "name": "Vmware"},
         {"ticker": "VOD", "name": "Vodafone"},
         {"ticker": "VOO", "name": "Vanguard S&P 500 ETF"},
          {"ticker": "VRSK", "name": "Verisk Analytics"},
          {"ticker": "VRSN", "name": "VeriSign"},
          {"ticker": "VRTX", "name": "Vertex Pharmaceuticals"},
         {"ticker": "VTI", "name": "Vanguard Total Stock Market ETF"},
         {"ticker": "VTR", "name": "Ventas"},
          {"ticker": "VTRS", "name": "Viatris"},
          {"ticker": "VXRT", "name": "Vaxart"},
           {"ticker": "VZ", "name": "Verizon"},
         {"ticker": "W", "name": "Wayfair"},
         {"ticker": "WAB", "name": "Westinghouse Air Brake Technologies"},
         {"ticker": "WAT", "name": "Waters"},
         {"ticker": "WBA", "name": "Walgreens"},
         {"ticker": "WBK", "name": "Westpac Banking"},
         {"ticker": "WCN", "name": "Waste Connections"},
          {"ticker": "WDAY", "name": "Workday"},
         {"ticker": "WDC", "name": "Western Digital"},
         {"ticker": "WEC", "name": "WEC Energy"},
          {"ticker": "WELL", "name": "Welltower"},
         {"ticker": "WFC", "name": "Wells Fargo"},
         {"ticker": "WHR", "name": "Whirlpool"},
          {"ticker": "WISH", "name": "ContextLogic"},
         {"ticker": "WIT", "name": "Wipro"},
         {"ticker": "WIX", "name": "Wix.com"},
          {"ticker": "WKHS", "name": "Workhorse"},
          {"ticker": "WLTW", "name": "Willis Towers Watson"},
           {"ticker": "WM", "name": "Waste Management"},
         {"ticker": "WMB", "name": "Williams Companies"},
         {"ticker": "WMG", "name": "Warner Music Group"},
         {"ticker": "WMT", "name": "Walmart"},
          {"ticker": "WOOF", "name": "Petco Health and Wellness"},
          {"ticker": "WORK", "name": "Slack"},
         {"ticker": "WPM", "name": "Wheaton Precious Metals Corp"},
         {"ticker": "WPP", "name": "WPP"},
         {"ticker": "WRK", "name": "Westrock"},
         {"ticker": "WST", "name": "West Pharmaceutical"},
           {"ticker": "WY", "name": "Weyerhaeuser"},
          {"ticker": "WYNN", "name": "Wynn Resorts"},
         {"ticker": "XEL", "name": "Xcel Energy"},
          {"ticker": "XLNX", "name": "Xilinx"},
          {"ticker": "XM", "name": "Qualtrics International"},
         {"ticker": "XOM", "name": "Exxon Mobil"},
           {"ticker": "XP", "name": "XP Inc"},
          {"ticker": "XPEV", "name": "Xpeng"},
         {"ticker": "XPO", "name": "XPO Logistics"},
         {"ticker": "XYL", "name": "Xylem"},
          {"ticker": "YNDX", "name": "Yandex"},
         {"ticker": "YUM", "name": "Yum!"},
          {"ticker": "YUMC", "name": "Yum China"},
           {"ticker": "Z", "name": "Zillow Class C"},
         {"ticker": "ZBH", "name": "Zimmer Biomet"},
          {"ticker": "ZBRA", "name": "Zebra Technologies"},
         {"ticker": "ZEN", "name": "Zendesk"},
         {"ticker": "ZG", "name": "Zillow Class A"},
         {"ticker": "ZI", "name": "ZoomInfo"},
         {"ticker": "ZM", "name": "Zoom"},
          {"ticker": "ZNGA", "name": "Zynga"},
         {"ticker": "ZOM", "name": "Zomedica"},
         {"ticker": "ZS", "name": "Zscaler"},
         {"ticker": "ZTO", "name": "ZTO Express"},
         {"ticker": "ZTS", "name": "Zoetis"}
  ];        
export default searchList;